networks:
  dockernet:
    # external: true
  # dockernet:
  #   ipam:
  #     config:
  #       - subnet: 172.23.0.0/16
services:
  # Dspace UI
  ui:
    container_name: dspace-ui
    image: dspace/dspace-angular:${DSPACE_VERSION}-dist
    build: 
      context: .
      dockerfile: ui.dockerfile
    env_file:
      - .env
    networks:
      - dockernet
    ports:
    - published: 4000
      target: 4000
    stdin_open: true
    tty: true

  # Dspace API
  api:
    container_name: dspace-api      
    image: dspace/dspace:${DSPACE_VERSION}
    build: 
      context: .
      dockerfile: api.dockerfile
    env_file:
      - .env
    depends_on:
      - dspacedb
    networks:
      - dockernet
    ports:
      - published: 8080
        target: 8080
      - published: 8000
        target: 8000
    stdin_open: true
    tty: true
    volumes:
    - assetstore:/dspace/assetstore
    - ./api/dspace/config:/dspace/config
    entrypoint:
    - /bin/bash
    - '-c'
    - |
      while (!</dev/tcp/dspacedb/5432) > /dev/null 2>&1; do sleep 1; done;
      /dspace/bin/dspace database migrate
      java -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace

  # Banco de Dados
  dspacedb:
    container_name: dspacedb
    image: dspace/dspace-postgres-pgcrypto:${DSPACE_VERSION}
    build: 
     context: ./docker/db/
    env_file:
      - .env
    networks:
      dockernet:
    ports:
      - published: 5432
        target: 5432
    stdin_open: true
    tty: true
    volumes:
      - pgdata:/pgdata

  # DSpace Solr
  dspacesolr:
    container_name: dspacesolr
    image: dspace/dspace-solr:${DSPACE_VERSION}
    build:
      context: ./docker/solr/
      additional_contexts: 
        solrconfigs: ./api/dspace/solr
    networks:
      dockernet:
    ports:
      - published: 8983
        target: 8983
    stdin_open: true
    tty: true
    working_dir: /var/solr/data
    volumes:
      - solr_data:/var/solr/data
    entrypoint:
    - /bin/bash
    - '-c'
    - |
      init-var-solr
      precreate-core authority /opt/solr/server/solr/configsets/authority
      cp -r /opt/solr/server/solr/configsets/authority/* authority
      precreate-core oai /opt/solr/server/solr/configsets/oai
      cp -r /opt/solr/server/solr/configsets/oai/* oai
      precreate-core search /opt/solr/server/solr/configsets/search
      cp -r /opt/solr/server/solr/configsets/search/* search
      precreate-core statistics /opt/solr/server/solr/configsets/statistics
      cp -r /opt/solr/server/solr/configsets/statistics/* statistics
      precreate-core qaevent /opt/solr/server/solr/configsets/qaevent
      cp -r /opt/solr/server/solr/configsets/qaevent/* qaevent
      precreate-core suggestion /opt/solr/server/solr/configsets/suggestion
      cp -r /opt/solr/server/solr/configsets/suggestion/* suggestion
      exec solr -f
volumes:
  assetstore:
  pgdata:
  solr_data: 







